module.exports = {
  usrNoAutori: 'Unauthorized user.',
  metodoNoValido: 'The method is not valid.',
  usrNoExiste: 'Username does not exist.',
  errRecupeDatos: 'Error getting data.',
  errGuardandoDatos: 'Error saving data.',
  faltaNombre: 'The name is missing.',
  faltaApellido: 'The last name is missing.',
  errCorreo: 'There is a problem with email.',
  clavesNoIgualesOVacias: 'The passwords are not the same or are empty.',
  errCreandoToken: 'Error creating token.',
  tokenNoValido: 'The token is not valid.',
  tokenNoExiste: 'The token does not exist.',
  registro: 'Signup',
  errRegistrando: 'Error registering user.',
  mailPreRegistro: 'Thank you for signup, to confirm your mail, please, follow the following link:',
  recuperarPass: 'Recover password',
  paraNuevaClaveEntraEn: 'To enter your new password, go to ',
  teEnviamosInstrucciones: 'We send you an email with instructions to recover your password, if you do not find it look for spam.',
  errActualiClaves: 'Error updating password.',
  noEsJpg: 'The file is not .jpg',
  errorDesconocido: 'Unknown error'
}
