module.exports = {
	usrNoAutori: 'Usuario no autorizado.',
	metodoNoValido: 'El método no es válido.',
	usrNoExiste: 'El usuario no existe',
	errRecupeDatos: 'Error recuperando datos.',
	errGuardandoDatos: 'Error guardando datos.',
	faltaNombre: 'Falta el nombre.',
	faltaApellido: 'Falta el apellido.',
	errCorreo: 'Hay un problema con el correo electrónico.',
	clavesNoIgualesOVacias: 'Las contraseñas no son iguales o están vacías.',
	errCreandoToken: 'Error creando token.',
	tokenNoValido: 'El token no es válido.',
	tokenNoExiste: 'El token no existe.',
	registro: 'Registro',
	errRegistrando: 'Error registrando usuario.',
	mailPreRegistro: 'Gracias por registrarse, para confirmar su correo, por favor, siga el siguiente enlace:',
	recuperarPass: 'Recuperar contraseña',
	paraNuevaClaveEntraEn: 'Para poner tu nueva contraseña entra en ',
	teEnviamosInstrucciones: 'Te enviamos un email con instrucciones para recuperar tu contraseña, si no lo encuentras busca en correo no deseado.',
	errActualiClaves: 'Error actualizando contraseña.',
	errorDesconocido: 'Error desconocido.'
};