module.exports = {
  errServidorVerLog: 'Error de servidor, ver log para detalles.',
  errorFormatoPeticion: 'El formato de la petición no es correcto.',

  usrNoAutori: 'Usuario no autorizado.',
  servicioNoValido: 'El servicio no es válido.',
  metodoNoValido: 'El método no es válido.',
  cuerpoNoJson: 'El cuerpo de la petición está mal formado, debe ser una cadena JSON.',
  errConexDatos: 'Error en la conexión de datos.',
  errConsultaDatos: 'Error consultando datos.',
  errRecupeDatos: 'Error recuperando datos.',

  errorNombreBlog: 'Hay un problema con el nombre de la sección.',
  elBlogNoExiste: 'La sección no existe.',
  elBlogYaExiste: 'La sección ya existe.',
  problemaCreandoBlog: 'Hubo algún problema creando la sección.',
  problemaActualiBlog: 'Hubo algún problema actualizando la sección.',
  problemaBorrandoBlog: 'Hubo algún problema borrando la sección. Podría ser que contenga artículos.',

  elAutorNoExiste: 'El autor no existe.',
  elAutorYaExiste: 'El autor ya existe.',
  problemaCreandoAutor: 'Hubo un problema creando el autor.',
  problemaActualiAutor: 'Hubo un problema actualizando el autor.',
  problemaBorrandoAutor: 'Hubo un problema borrando el autor. Podría ser que tenga artículos escritos.',
  errorUid: 'Hay un problema con el ID de usuario.',
  faltaFirmaAutor: 'Falta la firma del autor.',
  errorFirmaAutor: 'Hay un problema con la firma del autor.',
  faltaNombreUsr: 'Falta el nombre de usuario.',

  laCatNoExiste: 'La categoría no existe.',
  laCatYaExiste: 'La categoría ya existe.',
  problemaCreandoCat: 'Hubo algún problema creando la categoría.',
  problemaActualiCat: 'Hubo algún problema actualizando la categoría.',
  problemaBorrandoCat: 'Hubo algún problema borrando la categoría.',
  errorNombreCat: 'Hay un problema con el nombre de la categoría.',

  errorCreandoSetImg: 'Hubo algún problema creando el set de imágenes.',
  errorNombreArchivo: 'Hay un problema con el nombre del archivo.',
  debeSerJpgPng: 'El archivo debe ser una imagen jpg o png.',
  errorBorrandoSetImg: 'Hubo algún problema eliminando el set de imágenes.',
  noExisteBlogParaImg: 'No existe la sección para las imágenes.',
  elArtiOCatNoExiste: 'El artículo o categoría no existe.',

  errorCreandoArticulo: 'Hubo algún problema creando el artículo.',
  errorActualiArticulo: 'Hubo algún problema actualizando el artículo.',
  errorBorrarArticulo: 'Hubo algún problema eliminando el artículo.',
  elArticuloNoExiste: 'El artículo no existe.',
  elArticuloYaExiste: 'Ya hay un artículo con ese título.',
  faltaTitulo: 'Falta el título.',
  errorFechaPublicado: 'La fecha de publicación no es correcta.',
  errorAuxFecha: 'La fecha auxiliar no es correcta.'
}
