module.exports = {
	usrNoAutori: 'Usuario no autorizado',
	servicioNoValido: 'El servicio no es válido',
	metodoNoValido: 'El método no es válido',
	cuerpoNoJson: 'El cuerpo de la petición está mal formado, debe ser una cadena JSON',
	faltaId: 'Falta ID de contenido',
	faltaConteEn: 'Falta contenido en inglés',
	faltaConteEs: 'Falta contenido en español',
	faltaContenido: 'Falta el contenido',
	errConexDatos: 'Error en la conexión de datos',
	errConsultaDatos: 'Error consultando datos',
	errRecupeDatos: 'Error recuperando datos',
	noHayContenidos: 'No existen contenidos',
	elConteNoExiste: 'El contenido no existe',
	conteDuplicado: 'Contenido duplicado',
	noPudoCrearConte: 'No se pudo crear el contenido',
	noPudoActualiConte: 'No se pudo actualizar el contenido',
	ningunConteBorrado: 'Ningún contenido eliminado',
	noPudoBorrarConte: 'No se pudo eliminar el contenido'
};