module.exports = {
	usrNoAutori: 'Unauthorized user.',
	servicioNoValido: 'The service is not valid.',
	metodoNoValido: 'The method is not valid.',
	cuerpoNoJson: 'The body of the request is malformed, it must be a JSON string.',
	faltaId: 'Missing content ID.',
	faltaConteEn: 'Missing content in English.',
	faltaConteEs: 'Missing content in Spanish.',
	faltaContenido: 'Content is missing.',
	errConexDatos: 'Error in the data connection.',
	errConsultaDatos: 'Data query error.',
	errRecupeDatos: 'Error recovering data.',
	noHayContenidos: 'There are no contents.',
	elConteNoExiste: 'The content does not exist.',
	conteDuplicado: 'Duplicate content.',
	noPudoCrearConte: 'Content could not be created.',
	noPudoActualiConte: 'Content could not be updated.',
	ningunConteBorrado: 'No content removed.',
	noPudoBorrarConte: 'The content could not be deleted.'
};